version: '3'

services:
        web:
                image: nginx
                build: ./web
                ports:
                        - 80:80
                volumes:
                        - ./web/config/server.conf:/etc/nginx/conf.d/default.conf
                        - ./web/dist/:/usr/share/nginx/html
                        - data-volume:/usr/share/nginx/DATA
        scraper:
                image: nikokozak/pythontest
                build: ./scraper
                volumes:
                        - data-volume:/usr/DATA:rw

volumes:
        data-volume:
                
